version: '2'

networks:
  test:

services:

  # ca_org1:
  #   image: hyperledger/fabric-ca:1.5.6
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=7054
  #     - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #      - ./fabric-ca/org1:/etc/hyperledger/fabric-ca-server
  #   container_name: ca.org1.example.com
  #   hostname: ca.org1.example.com
  #   networks:
  #     - test
  ca_farmer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.farmer.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/farmer:/etc/hyperledger/fabric-ca-server
    container_name: ca.farmer.example.com
    hostname: ca.farmer.example.com
    networks:
      - test

  ca_distributor:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.distributor.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/distributor:/etc/hyperledger/fabric-ca-server
    container_name: ca.distributor.example.com
    hostname: ca.distributor.example.com
    networks:
      - test

  ca_consumer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.consumer.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/consumer:/etc/hyperledger/fabric-ca-server
    container_name: ca.consumer.example.com
    hostname: ca.consumer.example.com
    networks:
      - test

  ca_manufacturer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturer.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1056
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "1056:1056"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/manufacturer:/etc/hyperledger/fabric-ca-server
    container_name: ca.manufacturer.example.com
    hostname: ca.manufacturer.example.com
    networks:
      - test

  ca_retailer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "1054:1054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/retailer:/etc/hyperledger/fabric-ca-server
    container_name: ca.retailer.example.com
    hostname: ca.retailer.example.com
    networks:
      - test

  ca_wholesaler:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.wholesaler.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "2054:2054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/wholesaler:/etc/hyperledger/fabric-ca-server
    container_name: ca.wholesaler.example.com
    hostname: ca.wholesaler.example.com
    networks:
      - test
  ca_orderer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - test
